### ISSUE TITLE
EAM: Change RequiredResources numCPU to allow fractional cpus

### ISSUE THREAD

**Issue by gainsley** [camaraproject/EdgeCloud#253]
**Problem description**
The Edge-Application-Management's current RequiredResources' numCPU field is an integer, which restricts vcpu resource allocation to whole vcpus. Notably Kubernetes allows for fractional vcpu allocation down to the millivcpu, to allow for very lightweight containers/microservices that do not use a lot of compute.

**Expected behavior**
Being able to specify required vcpus in milli-vcpu increments.

**Alternative solution**
None.

**Additional context**
The [GSMA Federation EWBI](https://www.gsma.com/solutions-and-impact/technologies/networks/gsma_resources/east-westbound-interface-apis-version-4-0/) already allows for this:
```
    Vcpu:
      type: string
      pattern: ^\d+((\.\d{1,3})|(m))?$
      description: Number of vcpus in whole, decimal up to millivcpu, or millivcpu format.
      example:
        whole:
          value: 2
        decimal:
          value: 0.500
        millivcpu:
          value: 500m
```
For VM-based deployments, fractional vcpus may not be allowed, but that should be implementation dependent. For example a VM deployed via Kata-containers (kube-virt) on a Kubernetes cluster may allow for fractional vcpus.
